### ISSUE TITLE
Support sfc_to_geoms and function naming

### ISSUE THREAD

**Issue by latot** [JosiahParry/sfconversions#8]
Hi, the actual functions like ```sfc_to_geom``` works from a List, not from a sfc column, which is pretty weird... that would be something ```sf_to_geoms```.

At the same point, would be great have a function for sfc, to convert a ```sfc``` (column) to a ```Vec<Option<Geometry>>```.

Thx!

**Comment by JosiahParry** [comment]
The function does work on an sfc column. Note that an sfc is a list. Please provide a repro if you think it does not work.

**Comment by JosiahParry** [comment]
The function you are looking for also does exist: 

https://github.com/JosiahParry/sfconversions/blob/fce8e5b944a742b66881bf5763e114868d3b52d6/src/fromsf.rs#L58-L81

```rust
pub fn sfc_to_geometry(x: List) -> Vec<Option<Geometry>> {
    x
        .into_iter()
        .map(|(_, robj)| {
            let geo = sfg_to_geom(robj);
            match geo {
                Ok(g) => Some(g.geom),
                Err(_) => None
            }
        }).collect::<Vec<Option<Geometry>>>()
}
```

**Comment by JosiahParry** [comment]
I'm sorry, I do not follow the logic. You should use `sf::st_geometry()` to get the geometry out of sf object. To get an Robj into a List you can use `List::try_from(x).unwrap()`

Or you can use geoarrow-r and arrow-extendr to extract everything as a recordbatch in arrow-rs. Then the geometry column can be iterated over using geo-types if you'd like.
